import { getProjectRoute } from "@/utils/constants";

import {
  ProjectHeatmapLevel,
  ProjectOverviewRecord,
  ProjectTaskCounts,
  ProjectWorkflow,
  ProjectWorkflowTask,
} from "./types";

const createHeatmap = (
  mediumDays: number[],
  highDays: number[],
  pipelineId?: string,
) =>
  Array.from({ length: 31 }, (_, index) => {
    const day = index + 1;
    const level: ProjectHeatmapLevel = highDays.includes(day)
      ? "high"
      : mediumDays.includes(day)
        ? "medium"
        : "low";

    return {
      day,
      level,
      pipelineId,
    };
  });

const buildWorkflowTaskCounts = (
  tasks: ProjectWorkflowTask[],
): ProjectTaskCounts => ({
  total: tasks.length,
  done: tasks.filter((task) => task.status === "done").length,
  inProgress: tasks.filter((task) =>
    ["todo", "in-progress", "review"].includes(task.status),
  ).length,
  blocked: tasks.filter((task) => task.status === "blocked").length,
});

const createWorkflow = (
  workflow: Omit<ProjectWorkflow, "taskCounts">,
): ProjectWorkflow => ({
  ...workflow,
  taskCounts: buildWorkflowTaskCounts(workflow.tasks),
});

const summarizeProjectCounts = (
  workflows: ProjectWorkflow[],
): ProjectTaskCounts =>
  workflows.reduce(
    (totals, workflow) => ({
      total: totals.total + workflow.taskCounts.total,
      done: totals.done + workflow.taskCounts.done,
      inProgress: totals.inProgress + workflow.taskCounts.inProgress,
      blocked: totals.blocked + workflow.taskCounts.blocked,
    }),
    { total: 0, done: 0, inProgress: 0, blocked: 0 },
  );

const mobileWorkflows: ProjectWorkflow[] = [
  createWorkflow({
    id: "mwf-design",
    name: "Design",
    description:
      "Research, wireframes, and visual signoff for the mobile release.",
    status: "complete",
    ownerId: "m2",
    teamId: "design",
    pipelineId: "design-phase",
    progress: 100,
    dueWindow: "Feb 10 - Feb 24",
    updatedAt: "2d ago",
    startedAt: "2026-02-10",
    targetEndDate: "2026-02-25",
    completedAt: "2026-02-24",
    tasks: [
      {
        id: "mwt-1",
        title: "Design Research Study",
        status: "done",
        priority: "high",
        assigneeId: "m2",
        teamId: "design",
        pipelineId: "design-phase",
        dueDate: "2026-02-13",
        updatedAt: "6d ago",
        subtasks: [
          {
            id: "mws-1",
            title: "Interview script approved",
            status: "done",
            assigneeId: "m1",
            dueDate: "2026-02-11",
            updatedAt: "1w ago",
          },
          {
            id: "mws-2",
            title: "Research summary posted",
            status: "done",
            assigneeId: "m2",
            dueDate: "2026-02-13",
            updatedAt: "6d ago",
          },
        ],
      },
      {
        id: "mwt-2",
        title: "Low Fidelity Wireframes",
        status: "done",
        priority: "high",
        assigneeId: "m2",
        teamId: "design",
        pipelineId: "design-phase",
        dueDate: "2026-02-17",
        updatedAt: "5d ago",
        subtasks: [
          {
            id: "mws-3",
            title: "Core flow sketches",
            status: "done",
            assigneeId: "m2",
            dueDate: "2026-02-15",
            updatedAt: "5d ago",
          },
          {
            id: "mws-4",
            title: "Navigation map review",
            status: "done",
            assigneeId: "m1",
            dueDate: "2026-02-17",
            updatedAt: "5d ago",
          },
        ],
      },
      {
        id: "mwt-3",
        title: "High Fidelity Mockups",
        status: "done",
        priority: "medium",
        assigneeId: "m2",
        teamId: "design",
        pipelineId: "design-phase",
        dueDate: "2026-02-21",
        updatedAt: "4d ago",
        subtasks: [
          {
            id: "mws-5",
            title: "Design tokens synced",
            status: "done",
            assigneeId: "m2",
            dueDate: "2026-02-19",
            updatedAt: "4d ago",
          },
          {
            id: "mws-6",
            title: "Prototype comments resolved",
            status: "done",
            assigneeId: "m3",
            dueDate: "2026-02-21",
            updatedAt: "4d ago",
          },
        ],
      },
      {
        id: "mwt-4",
        title: "Engineering Handoff",
        status: "done",
        priority: "medium",
        assigneeId: "m1",
        teamId: "product",
        pipelineId: "design-phase",
        dueDate: "2026-02-24",
        updatedAt: "2d ago",
      },
    ],
  }),
  createWorkflow({
    id: "mwf-development",
    name: "Development",
    description: "Build the authenticated, payment, and notification flows.",
    status: "at-risk",
    ownerId: "m3",
    teamId: "frontend",
    pipelineId: "development-phase",
    progress: 64,
    dueWindow: "Feb 20 - Mar 20",
    updatedAt: "2h ago",
    startedAt: "2026-02-20",
    targetEndDate: "2026-03-20",
    tasks: [
      {
        id: "mwt-5",
        title: "Authentication Flow",
        status: "in-progress",
        priority: "high",
        assigneeId: "m3",
        teamId: "frontend",
        pipelineId: "development-phase",
        dueDate: "2026-03-08",
        updatedAt: "2h ago",
        subtasks: [
          {
            id: "mws-7",
            title: "Session guards",
            status: "done",
            assigneeId: "m3",
            dueDate: "2026-03-04",
            updatedAt: "5h ago",
          },
          {
            id: "mws-8",
            title: "Password reset screens",
            status: "in-progress",
            assigneeId: "m4",
            dueDate: "2026-03-08",
            updatedAt: "2h ago",
          },
        ],
      },
      {
        id: "mwt-6",
        title: "Payments Integration",
        status: "blocked",
        priority: "high",
        assigneeId: "m6",
        teamId: "frontend",
        pipelineId: "development-phase",
        dueDate: "2026-03-12",
        updatedAt: "Today",
        subtasks: [
          {
            id: "mws-9",
            title: "Webhook signature checks",
            status: "done",
            assigneeId: "m6",
            dueDate: "2026-03-07",
            updatedAt: "Today",
          },
          {
            id: "mws-10",
            title: "Provider retry handling",
            status: "blocked",
            assigneeId: "m6",
            dueDate: "2026-03-10",
            updatedAt: "Today",
          },
          {
            id: "mws-11",
            title: "Sandbox fallback mode",
            status: "todo",
            assigneeId: "m4",
            dueDate: "2026-03-12",
            updatedAt: "Today",
          },
        ],
      },
      {
        id: "mwt-7",
        title: "Push Notifications",
        status: "review",
        priority: "medium",
        assigneeId: "m4",
        teamId: "frontend",
        pipelineId: "development-phase",
        dueDate: "2026-03-15",
        updatedAt: "Today",
        subtasks: [
          {
            id: "mws-12",
            title: "Permission flow copy",
            status: "done",
            assigneeId: "m2",
            dueDate: "2026-03-11",
            updatedAt: "Today",
          },
          {
            id: "mws-13",
            title: "Foreground notification states",
            status: "review",
            assigneeId: "m4",
            dueDate: "2026-03-15",
            updatedAt: "Today",
          },
        ],
      },
      {
        id: "mwt-8",
        title: "Offline Sync Basics",
        status: "todo",
        priority: "medium",
        assigneeId: "m4",
        teamId: "frontend",
        pipelineId: "development-phase",
        dueDate: "2026-03-18",
        updatedAt: "Today",
        subtasks: [
          {
            id: "mws-14",
            title: "Queue model",
            status: "todo",
            assigneeId: "m4",
            dueDate: "2026-03-16",
            updatedAt: "Today",
          },
          {
            id: "mws-15",
            title: "Conflict banner",
            status: "todo",
            assigneeId: "m3",
            dueDate: "2026-03-18",
            updatedAt: "Today",
          },
        ],
      },
    ],
  }),
  createWorkflow({
    id: "mwf-qa-launch",
    name: "QA & Launch",
    description: "Regression, store readiness, and release submission.",
    status: "on-track",
    ownerId: "m5",
    teamId: "qa",
    pipelineId: "qa-launch",
    progress: 38,
    dueWindow: "Mar 10 - Mar 31",
    updatedAt: "Yesterday",
    startedAt: "2026-03-10",
    targetEndDate: "2026-03-31",
    tasks: [
      {
        id: "mwt-9",
        title: "Regression Testing",
        status: "in-progress",
        priority: "high",
        assigneeId: "m5",
        teamId: "qa",
        pipelineId: "qa-launch",
        dueDate: "2026-03-20",
        updatedAt: "Yesterday",
        subtasks: [
          {
            id: "mws-16",
            title: "iOS smoke pass",
            status: "in-progress",
            assigneeId: "m5",
            dueDate: "2026-03-18",
            updatedAt: "Yesterday",
          },
          {
            id: "mws-17",
            title: "Android smoke pass",
            status: "done",
            assigneeId: "m5",
            dueDate: "2026-03-17",
            updatedAt: "Yesterday",
          },
        ],
      },
      {
        id: "mwt-10",
        title: "Store Metadata Review",
        status: "review",
        priority: "medium",
        assigneeId: "m1",
        teamId: "product",
        pipelineId: "qa-launch",
        dueDate: "2026-03-24",
        updatedAt: "Yesterday",
      },
      {
        id: "mwt-11",
        title: "App Store Submission",
        status: "todo",
        priority: "high",
        assigneeId: "m1",
        teamId: "product",
        pipelineId: "qa-launch",
        dueDate: "2026-03-30",
        updatedAt: "Yesterday",
        subtasks: [
          {
            id: "mws-18",
            title: "Privacy answers",
            status: "todo",
            assigneeId: "m1",
            dueDate: "2026-03-26",
            updatedAt: "Yesterday",
          },
          {
            id: "mws-19",
            title: "Build notes",
            status: "todo",
            assigneeId: "m5",
            dueDate: "2026-03-28",
            updatedAt: "Yesterday",
          },
        ],
      },
    ],
  }),
];

const mobileApp: ProjectOverviewRecord = {
  id: "mobile-app",
  emoji: "📱",
  name: "Mobile App",
  status: "on-track",
  summary:
    "Track delivery across design, build, and launch in one compact operational view.",
  dueWindow: "Feb 10 - Mar 31",
  startDate: "2026-02-10",
  progress: 68,
  riskHint: "Payments integration is still the main release pressure.",
  taskCounts: summarizeProjectCounts(mobileWorkflows),
  pipelines: [
    {
      id: "design-phase",
      name: "Design",
      description: "Research, wireframes, and final visual signoff.",
      taskCounts: mobileWorkflows[0].taskCounts,
      deadlineCount: 2,
      dueWindow: "Feb 10 - Feb 24",
      progress: 100,
      riskHint: "Design is closed and ready for build handoff.",
      heatmap: createHeatmap([2, 4, 6, 8], [5], "design-phase"),
    },
    {
      id: "development-phase",
      name: "Development",
      description: "Core implementation of the approved mobile flows.",
      taskCounts: mobileWorkflows[1].taskCounts,
      deadlineCount: 3,
      dueWindow: "Feb 20 - Mar 20",
      progress: 64,
      riskHint: "Payments integration is holding back the cleanest burn-down.",
      heatmap: createHeatmap(
        [3, 6, 7, 9, 12, 14, 19],
        [11, 16, 24],
        "development-phase",
      ),
    },
    {
      id: "qa-launch",
      name: "QA & Launch",
      description: "Verification, launch prep, and store submission.",
      taskCounts: mobileWorkflows[2].taskCounts,
      deadlineCount: 2,
      dueWindow: "Mar 10 - Mar 31",
      progress: 38,
      riskHint:
        "Store materials are queued, but the regression queue is still open.",
      heatmap: createHeatmap([18, 21, 23, 29], [20, 26, 30], "qa-launch"),
    },
  ],
  members: [
    {
      id: "m1",
      name: "Tobe Eze",
      initials: "TE",
      role: "Product",
      active: true,
      teamIds: ["product"],
    },
    {
      id: "m2",
      name: "Amara Ude",
      initials: "AU",
      role: "Design",
      active: true,
      teamIds: ["design"],
    },
    {
      id: "m3",
      name: "Samuel Obi",
      initials: "SO",
      role: "Frontend",
      active: true,
      teamIds: ["frontend"],
    },
    {
      id: "m4",
      name: "Chioma Duru",
      initials: "CD",
      role: "Frontend",
      active: true,
      teamIds: ["frontend"],
    },
    {
      id: "m5",
      name: "Zina Ayo",
      initials: "ZA",
      role: "QA",
      active: true,
      teamIds: ["qa"],
    },
    {
      id: "m6",
      name: "Boma Ita",
      initials: "BI",
      role: "Backend",
      active: true,
      teamIds: ["frontend", "product"],
    },
  ],
  milestones: [
    {
      id: "mm1",
      title: "Design signoff",
      dueDate: "2026-02-24",
      completion: 100,
      pipelineId: "design-phase",
      teamId: "design",
      owner: "Amara Ude",
    },
    {
      id: "mm2",
      title: "Payments integration ready",
      dueDate: "2026-03-12",
      completion: 62,
      pipelineId: "development-phase",
      teamId: "frontend",
      owner: "Boma Ita",
    },
    {
      id: "mm3",
      title: "Regression pass",
      dueDate: "2026-03-20",
      completion: 38,
      pipelineId: "qa-launch",
      teamId: "qa",
      owner: "Zina Ayo",
    },
    {
      id: "mm4",
      title: "App store submission",
      dueDate: "2026-03-30",
      completion: 12,
      pipelineId: "qa-launch",
      teamId: "product",
      owner: "Tobe Eze",
    },
  ],
  risks: [
    {
      id: "mr1",
      kind: "risk",
      title: "Provider payload drift",
      description:
        "The payments provider keeps changing staging responses, which is stretching integration work.",
      severity: "high",
      owner: "Boma Ita",
      status: "Watching",
      pipelineId: "development-phase",
      teamId: "frontend",
    },
    {
      id: "mr2",
      kind: "risk",
      title: "Store assets still pending",
      description:
        "Final launch graphics still need one export pass for the submission package.",
      severity: "medium",
      owner: "Amara Ude",
      status: "Mitigating",
      pipelineId: "qa-launch",
      teamId: "design",
    },
    {
      id: "mr3",
      kind: "issue",
      title: "Push notification cold start bug",
      description:
        "A subset of iOS devices is dropping token refresh on cold launch.",
      severity: "high",
      owner: "Samuel Obi",
      status: "In progress",
      pipelineId: "development-phase",
      teamId: "frontend",
    },
    {
      id: "mr4",
      kind: "issue",
      title: "App icon size mismatch",
      description:
        "One required icon export is missing from the current design pack.",
      severity: "low",
      owner: "Amara Ude",
      status: "Queued",
      pipelineId: "qa-launch",
      teamId: "design",
    },
  ],
  activities: [
    {
      id: "ma1",
      actor: "Amara Ude",
      actorInitials: "AU",
      summary:
        "closed final mockups and handed the design package to engineering.",
      createdAt: "2h ago",
      pipelineId: "design-phase",
      teamId: "design",
    },
    {
      id: "ma2",
      actor: "Samuel Obi",
      actorInitials: "SO",
      summary: "moved the authentication flow to the final integration pass.",
      createdAt: "5h ago",
      pipelineId: "development-phase",
      teamId: "frontend",
    },
    {
      id: "ma3",
      actor: "Boma Ita",
      actorInitials: "BI",
      summary: "flagged a new payments provider payload change in staging.",
      createdAt: "Today",
      pipelineId: "development-phase",
      teamId: "frontend",
    },
    {
      id: "ma4",
      actor: "Zina Ayo",
      actorInitials: "ZA",
      summary:
        "started the iOS smoke pass and linked the latest issues to launch QA.",
      createdAt: "Yesterday",
      pipelineId: "qa-launch",
      teamId: "qa",
    },
  ],
  teams: [
    {
      id: "product",
      name: "Product",
      focus: "Scope, priorities, and launch decisions",
      memberIds: ["m1", "m6"],
      pipelineIds: ["design-phase", "qa-launch"],
      taskCounts: { total: 3, done: 1, inProgress: 2, blocked: 0 },
      progress: 58,
      dueWindow: "Feb 12 - Mar 30",
    },
    {
      id: "design",
      name: "Design",
      focus: "UX, visual polish, and launch assets",
      memberIds: ["m2"],
      pipelineIds: ["design-phase", "qa-launch"],
      taskCounts: { total: 4, done: 4, inProgress: 0, blocked: 0 },
      progress: 100,
      dueWindow: "Feb 10 - Feb 24",
    },
    {
      id: "frontend",
      name: "Frontend",
      focus: "Feature implementation and integration",
      memberIds: ["m3", "m4", "m6"],
      pipelineIds: ["development-phase"],
      taskCounts: mobileWorkflows[1].taskCounts,
      progress: 64,
      dueWindow: "Feb 20 - Mar 20",
    },
    {
      id: "qa",
      name: "Quality",
      focus: "Verification and release readiness",
      memberIds: ["m5"],
      pipelineIds: ["qa-launch"],
      taskCounts: mobileWorkflows[2].taskCounts,
      progress: 38,
      dueWindow: "Mar 10 - Mar 31",
    },
  ],
  heatmap: createHeatmap(
    [2, 3, 5, 7, 9, 10, 12, 14, 16, 19, 22, 24, 27, 29],
    [11, 17, 23, 30],
  ),
  workflows: mobileWorkflows,
};

const growthWorkflows: ProjectWorkflow[] = [
  createWorkflow({
    id: "gwf-strategy",
    name: "Strategy & Offer",
    description: "Audience definition, offer framing, and launch plan lock.",
    status: "complete",
    ownerId: "g1",
    teamId: "strategy",
    pipelineId: "strategy-phase",
    progress: 100,
    dueWindow: "Feb 8 - Feb 20",
    updatedAt: "3d ago",
    startedAt: "2026-02-08",
    targetEndDate: "2026-02-21",
    completedAt: "2026-02-20",
    tasks: [
      {
        id: "gwt-1",
        title: "Audience segmentation",
        status: "done",
        priority: "high",
        assigneeId: "g1",
        teamId: "strategy",
        pipelineId: "strategy-phase",
        dueDate: "2026-02-12",
        updatedAt: "1w ago",
        subtasks: [
          {
            id: "gws-1",
            title: "Primary persona cuts",
            status: "done",
            assigneeId: "g1",
            dueDate: "2026-02-10",
            updatedAt: "1w ago",
          },
          {
            id: "gws-2",
            title: "Value prop review",
            status: "done",
            assigneeId: "g2",
            dueDate: "2026-02-12",
            updatedAt: "1w ago",
          },
        ],
      },
      {
        id: "gwt-2",
        title: "Launch messaging brief",
        status: "done",
        priority: "high",
        assigneeId: "g2",
        teamId: "creative",
        pipelineId: "strategy-phase",
        dueDate: "2026-02-16",
        updatedAt: "6d ago",
      },
      {
        id: "gwt-3",
        title: "Channel mix approval",
        status: "done",
        priority: "medium",
        assigneeId: "g4",
        teamId: "paid-media",
        pipelineId: "strategy-phase",
        dueDate: "2026-02-20",
        updatedAt: "3d ago",
      },
    ],
  }),
  createWorkflow({
    id: "gwf-creative",
    name: "Creative Production",
    description: "Landing copy, asset production, and launch-ready variants.",
    status: "on-track",
    ownerId: "g2",
    teamId: "creative",
    pipelineId: "creative-phase",
    progress: 58,
    dueWindow: "Feb 18 - Mar 18",
    updatedAt: "4h ago",
    startedAt: "2026-02-18",
    targetEndDate: "2026-03-18",
    tasks: [
      {
        id: "gwt-4",
        title: "Landing page copy",
        status: "review",
        priority: "high",
        assigneeId: "g2",
        teamId: "creative",
        pipelineId: "creative-phase",
        dueDate: "2026-03-07",
        updatedAt: "4h ago",
        subtasks: [
          {
            id: "gws-3",
            title: "Headline variants",
            status: "done",
            assigneeId: "g2",
            dueDate: "2026-03-03",
            updatedAt: "Yesterday",
          },
          {
            id: "gws-4",
            title: "CTA review",
            status: "review",
            assigneeId: "g1",
            dueDate: "2026-03-07",
            updatedAt: "4h ago",
          },
        ],
      },
      {
        id: "gwt-5",
        title: "Paid social asset pack",
        status: "in-progress",
        priority: "high",
        assigneeId: "g3",
        teamId: "creative",
        pipelineId: "creative-phase",
        dueDate: "2026-03-10",
        updatedAt: "Today",
        subtasks: [
          {
            id: "gws-5",
            title: "Square static exports",
            status: "done",
            assigneeId: "g3",
            dueDate: "2026-03-05",
            updatedAt: "Today",
          },
          {
            id: "gws-6",
            title: "Story variants",
            status: "in-progress",
            assigneeId: "g3",
            dueDate: "2026-03-10",
            updatedAt: "Today",
          },
        ],
      },
      {
        id: "gwt-6",
        title: "Lifecycle email drafts",
        status: "todo",
        priority: "medium",
        assigneeId: "g2",
        teamId: "creative",
        pipelineId: "creative-phase",
        dueDate: "2026-03-14",
        updatedAt: "Today",
      },
    ],
  }),
  createWorkflow({
    id: "gwf-launch",
    name: "Launch Optimisation",
    description: "Budget tuning, experiment setup, and performance watch.",
    status: "at-risk",
    ownerId: "g4",
    teamId: "paid-media",
    pipelineId: "launch-phase",
    progress: 42,
    dueWindow: "Mar 1 - Mar 28",
    updatedAt: "Today",
    startedAt: "2026-03-01",
    targetEndDate: "2026-03-28",
    tasks: [
      {
        id: "gwt-7",
        title: "Campaign budget pacing",
        status: "in-progress",
        priority: "high",
        assigneeId: "g4",
        teamId: "paid-media",
        pipelineId: "launch-phase",
        dueDate: "2026-03-11",
        updatedAt: "Today",
        subtasks: [
          {
            id: "gws-7",
            title: "Daily cap audit",
            status: "done",
            assigneeId: "g4",
            dueDate: "2026-03-05",
            updatedAt: "Today",
          },
          {
            id: "gws-8",
            title: "Bid floor tuning",
            status: "in-progress",
            assigneeId: "g4",
            dueDate: "2026-03-11",
            updatedAt: "Today",
          },
        ],
      },
      {
        id: "gwt-8",
        title: "Experiment readout",
        status: "blocked",
        priority: "high",
        assigneeId: "g1",
        teamId: "strategy",
        pipelineId: "launch-phase",
        dueDate: "2026-03-15",
        updatedAt: "Today",
      },
      {
        id: "gwt-9",
        title: "Retargeting refresh",
        status: "todo",
        priority: "medium",
        assigneeId: "g3",
        teamId: "creative",
        pipelineId: "launch-phase",
        dueDate: "2026-03-18",
        updatedAt: "Today",
      },
    ],
  }),
];

const growthCampaign: ProjectOverviewRecord = {
  id: "growth-campaign",
  emoji: "📈",
  name: "Growth Campaign",
  status: "at-risk",
  summary:
    "A compact operating view for strategy, creative production, and launch optimisation.",
  dueWindow: "Feb 8 - Mar 28",
  startDate: "2026-02-08",
  progress: 59,
  riskHint: "Experiment readout delays are limiting clean budget optimisation.",
  taskCounts: summarizeProjectCounts(growthWorkflows),
  pipelines: [
    {
      id: "strategy-phase",
      name: "Strategy",
      description: "Audience, offer, and channel planning.",
      taskCounts: growthWorkflows[0].taskCounts,
      deadlineCount: 2,
      dueWindow: "Feb 8 - Feb 20",
      progress: 100,
      riskHint: "Strategy is locked and ready for scale.",
      heatmap: createHeatmap([2, 5, 8], [6], "strategy-phase"),
    },
    {
      id: "creative-phase",
      name: "Creative",
      description: "Landing pages, assets, and lifecycle creative.",
      taskCounts: growthWorkflows[1].taskCounts,
      deadlineCount: 3,
      dueWindow: "Feb 18 - Mar 18",
      progress: 58,
      riskHint: "Creative review is moving, but approvals are still stacked.",
      heatmap: createHeatmap([4, 8, 12, 15, 18], [10, 14], "creative-phase"),
    },
    {
      id: "launch-phase",
      name: "Launch",
      description: "Budget pacing, experiments, and optimisation.",
      taskCounts: growthWorkflows[2].taskCounts,
      deadlineCount: 2,
      dueWindow: "Mar 1 - Mar 28",
      progress: 42,
      riskHint: "Budget tuning depends on the pending experiment readout.",
      heatmap: createHeatmap([16, 19, 22, 26], [18, 24, 29], "launch-phase"),
    },
  ],
  members: [
    {
      id: "g1",
      name: "Nora Hale",
      initials: "NH",
      role: "Strategy",
      active: true,
      teamIds: ["strategy"],
    },
    {
      id: "g2",
      name: "Mina Cole",
      initials: "MC",
      role: "Copy",
      active: true,
      teamIds: ["creative"],
    },
    {
      id: "g3",
      name: "Jules Hart",
      initials: "JH",
      role: "Design",
      active: true,
      teamIds: ["creative"],
    },
    {
      id: "g4",
      name: "Ife Kanu",
      initials: "IK",
      role: "Paid Media",
      active: true,
      teamIds: ["paid-media"],
    },
  ],
  milestones: [
    {
      id: "gm1",
      title: "Messaging brief approved",
      dueDate: "2026-02-20",
      completion: 100,
      pipelineId: "strategy-phase",
      teamId: "strategy",
      owner: "Nora Hale",
    },
    {
      id: "gm2",
      title: "Landing page creative ready",
      dueDate: "2026-03-07",
      completion: 58,
      pipelineId: "creative-phase",
      teamId: "creative",
      owner: "Mina Cole",
    },
    {
      id: "gm3",
      title: "Budget pacing baseline",
      dueDate: "2026-03-11",
      completion: 42,
      pipelineId: "launch-phase",
      teamId: "paid-media",
      owner: "Ife Kanu",
    },
  ],
  risks: [
    {
      id: "gr1",
      kind: "risk",
      title: "Experiment readout is late",
      description:
        "The holdout results are not in yet, which makes launch optimisation less precise.",
      severity: "high",
      owner: "Nora Hale",
      status: "Watching",
      pipelineId: "launch-phase",
      teamId: "strategy",
    },
    {
      id: "gr2",
      kind: "risk",
      title: "Creative approvals stacking",
      description:
        "Two landing page variants still need final signoff before export.",
      severity: "medium",
      owner: "Mina Cole",
      status: "Mitigating",
      pipelineId: "creative-phase",
      teamId: "creative",
    },
    {
      id: "gr3",
      kind: "issue",
      title: "Retargeting audience size dropped",
      description:
        "The latest sync reduced audience volume below the expected launch floor.",
      severity: "medium",
      owner: "Ife Kanu",
      status: "Open",
      pipelineId: "launch-phase",
      teamId: "paid-media",
    },
  ],
  activities: [
    {
      id: "ga1",
      actor: "Mina Cole",
      actorInitials: "MC",
      summary: "moved the headline review into final approval.",
      createdAt: "1h ago",
      pipelineId: "creative-phase",
      teamId: "creative",
    },
    {
      id: "ga2",
      actor: "Ife Kanu",
      actorInitials: "IK",
      summary: "flagged the delayed experiment readout on the launch board.",
      createdAt: "Today",
      pipelineId: "launch-phase",
      teamId: "paid-media",
    },
    {
      id: "ga3",
      actor: "Nora Hale",
      actorInitials: "NH",
      summary: "approved the final audience segmentation set for launch.",
      createdAt: "Yesterday",
      pipelineId: "strategy-phase",
      teamId: "strategy",
    },
  ],
  teams: [
    {
      id: "strategy",
      name: "Strategy",
      focus: "Positioning, audience, and test framing",
      memberIds: ["g1"],
      pipelineIds: ["strategy-phase", "launch-phase"],
      taskCounts: { total: 2, done: 1, inProgress: 1, blocked: 0 },
      progress: 62,
      dueWindow: "Feb 8 - Mar 15",
    },
    {
      id: "creative",
      name: "Creative",
      focus: "Copy, design, and asset production",
      memberIds: ["g2", "g3"],
      pipelineIds: ["strategy-phase", "creative-phase", "launch-phase"],
      taskCounts: growthWorkflows[1].taskCounts,
      progress: 58,
      dueWindow: "Feb 18 - Mar 18",
    },
    {
      id: "paid-media",
      name: "Paid Media",
      focus: "Campaign setup and optimisation",
      memberIds: ["g4"],
      pipelineIds: ["launch-phase"],
      taskCounts: growthWorkflows[2].taskCounts,
      progress: 42,
      dueWindow: "Mar 1 - Mar 28",
    },
  ],
  heatmap: createHeatmap(
    [2, 4, 7, 9, 11, 14, 17, 20, 24, 27],
    [12, 18, 23, 29],
  ),
  workflows: growthWorkflows,
};

const opsWorkflows: ProjectWorkflow[] = [
  createWorkflow({
    id: "owf-process-design",
    name: "Process Design",
    description: "Map the operator journey, handoffs, and clear ownership.",
    status: "on-track",
    ownerId: "o1",
    teamId: "ops",
    pipelineId: "process-phase",
    progress: 72,
    dueWindow: "Feb 12 - Mar 14",
    updatedAt: "3h ago",
    startedAt: "2026-02-12",
    targetEndDate: "2026-03-14",
    tasks: [
      {
        id: "owt-1",
        title: "Operator journey map",
        status: "done",
        priority: "high",
        assigneeId: "o1",
        teamId: "ops",
        pipelineId: "process-phase",
        dueDate: "2026-02-25",
        updatedAt: "4d ago",
      },
      {
        id: "owt-2",
        title: "Ownership matrix",
        status: "review",
        priority: "high",
        assigneeId: "o3",
        teamId: "ops",
        pipelineId: "process-phase",
        dueDate: "2026-03-08",
        updatedAt: "3h ago",
        subtasks: [
          {
            id: "ows-1",
            title: "Escalation path review",
            status: "done",
            assigneeId: "o1",
            dueDate: "2026-03-04",
            updatedAt: "Yesterday",
          },
          {
            id: "ows-2",
            title: "Support handoff mapping",
            status: "review",
            assigneeId: "o3",
            dueDate: "2026-03-08",
            updatedAt: "3h ago",
          },
        ],
      },
      {
        id: "owt-3",
        title: "Approval checklist",
        status: "in-progress",
        priority: "medium",
        assigneeId: "o1",
        teamId: "ops",
        pipelineId: "process-phase",
        dueDate: "2026-03-12",
        updatedAt: "Today",
      },
    ],
  }),
  createWorkflow({
    id: "owf-automation",
    name: "Automation Rollout",
    description: "Connect triggers, pilot the workflow, and harden fallbacks.",
    status: "at-risk",
    ownerId: "o2",
    teamId: "automation",
    pipelineId: "automation-phase",
    progress: 36,
    dueWindow: "Mar 1 - Mar 26",
    updatedAt: "Today",
    startedAt: "2026-03-01",
    targetEndDate: "2026-03-26",
    tasks: [
      {
        id: "owt-4",
        title: "Webhook pilot",
        status: "blocked",
        priority: "high",
        assigneeId: "o2",
        teamId: "automation",
        pipelineId: "automation-phase",
        dueDate: "2026-03-10",
        updatedAt: "Today",
        subtasks: [
          {
            id: "ows-3",
            title: "Vendor allowlist",
            status: "blocked",
            assigneeId: "o2",
            dueDate: "2026-03-07",
            updatedAt: "Today",
          },
          {
            id: "ows-4",
            title: "Retry rules",
            status: "todo",
            assigneeId: "o2",
            dueDate: "2026-03-10",
            updatedAt: "Today",
          },
        ],
      },
      {
        id: "owt-5",
        title: "Fallback runbook",
        status: "in-progress",
        priority: "high",
        assigneeId: "o4",
        teamId: "enablement",
        pipelineId: "automation-phase",
        dueDate: "2026-03-16",
        updatedAt: "Today",
      },
      {
        id: "owt-6",
        title: "Pilot operator training",
        status: "todo",
        priority: "medium",
        assigneeId: "o3",
        teamId: "enablement",
        pipelineId: "automation-phase",
        dueDate: "2026-03-20",
        updatedAt: "Today",
      },
    ],
  }),
  createWorkflow({
    id: "owf-handoff",
    name: "Handoff & Training",
    description:
      "Document handoff rules, train teams, and close rollout readiness.",
    status: "on-track",
    ownerId: "o4",
    teamId: "enablement",
    pipelineId: "handoff-phase",
    progress: 44,
    dueWindow: "Mar 10 - Apr 4",
    updatedAt: "Yesterday",
    startedAt: "2026-03-10",
    targetEndDate: "2026-04-04",
    tasks: [
      {
        id: "owt-7",
        title: "Runbook draft",
        status: "review",
        priority: "medium",
        assigneeId: "o4",
        teamId: "enablement",
        pipelineId: "handoff-phase",
        dueDate: "2026-03-18",
        updatedAt: "Yesterday",
      },
      {
        id: "owt-8",
        title: "Operator training deck",
        status: "in-progress",
        priority: "medium",
        assigneeId: "o3",
        teamId: "enablement",
        pipelineId: "handoff-phase",
        dueDate: "2026-03-22",
        updatedAt: "Yesterday",
        subtasks: [
          {
            id: "ows-5",
            title: "Scenario slides",
            status: "done",
            assigneeId: "o3",
            dueDate: "2026-03-17",
            updatedAt: "Yesterday",
          },
          {
            id: "ows-6",
            title: "Escalation examples",
            status: "in-progress",
            assigneeId: "o4",
            dueDate: "2026-03-22",
            updatedAt: "Yesterday",
          },
        ],
      },
      {
        id: "owt-9",
        title: "Readiness review",
        status: "todo",
        priority: "high",
        assigneeId: "o1",
        teamId: "ops",
        pipelineId: "handoff-phase",
        dueDate: "2026-03-30",
        updatedAt: "Yesterday",
      },
    ],
  }),
];

const opsCommand: ProjectOverviewRecord = {
  id: "ops-command",
  emoji: "🧭",
  name: "Ops Command",
  status: "on-track",
  summary:
    "Coordinate process design, automation rollout, and enablement in one compact view.",
  dueWindow: "Feb 12 - Apr 4",
  startDate: "2026-02-12",
  progress: 51,
  riskHint: "Vendor approval is slowing down the automation pilot.",
  taskCounts: summarizeProjectCounts(opsWorkflows),
  pipelines: [
    {
      id: "process-phase",
      name: "Process",
      description: "Operator flow mapping and ownership definition.",
      taskCounts: opsWorkflows[0].taskCounts,
      deadlineCount: 2,
      dueWindow: "Feb 12 - Mar 14",
      progress: 72,
      riskHint: "Process work is moving, with one ownership review still open.",
      heatmap: createHeatmap([2, 4, 7, 11], [8], "process-phase"),
    },
    {
      id: "automation-phase",
      name: "Automation",
      description: "Pilot rollout, triggers, and fallback logic.",
      taskCounts: opsWorkflows[1].taskCounts,
      deadlineCount: 2,
      dueWindow: "Mar 1 - Mar 26",
      progress: 36,
      riskHint: "Vendor approval is still the blocking dependency.",
      heatmap: createHeatmap([14, 17, 19, 22], [18, 24], "automation-phase"),
    },
    {
      id: "handoff-phase",
      name: "Handoff",
      description: "Training, runbooks, and rollout readiness.",
      taskCounts: opsWorkflows[2].taskCounts,
      deadlineCount: 2,
      dueWindow: "Mar 10 - Apr 4",
      progress: 44,
      riskHint:
        "Training content is moving, but readiness signoff is still pending.",
      heatmap: createHeatmap([21, 24, 26, 29], [27, 30], "handoff-phase"),
    },
  ],
  members: [
    {
      id: "o1",
      name: "Kemi Fox",
      initials: "KF",
      role: "Operations",
      active: true,
      teamIds: ["ops"],
    },
    {
      id: "o2",
      name: "Ray Stone",
      initials: "RS",
      role: "Automation",
      active: true,
      teamIds: ["automation"],
    },
    {
      id: "o3",
      name: "Tari Ben",
      initials: "TB",
      role: "Ops Specialist",
      active: true,
      teamIds: ["ops", "enablement"],
    },
    {
      id: "o4",
      name: "Jade Moss",
      initials: "JM",
      role: "Enablement",
      active: true,
      teamIds: ["enablement"],
    },
  ],
  milestones: [
    {
      id: "om1",
      title: "Ownership matrix review",
      dueDate: "2026-03-08",
      completion: 72,
      pipelineId: "process-phase",
      teamId: "ops",
      owner: "Tari Ben",
    },
    {
      id: "om2",
      title: "Webhook pilot approval",
      dueDate: "2026-03-10",
      completion: 34,
      pipelineId: "automation-phase",
      teamId: "automation",
      owner: "Ray Stone",
    },
    {
      id: "om3",
      title: "Training deck review",
      dueDate: "2026-03-22",
      completion: 44,
      pipelineId: "handoff-phase",
      teamId: "enablement",
      owner: "Jade Moss",
    },
  ],
  risks: [
    {
      id: "or1",
      kind: "risk",
      title: "Vendor pilot approval delay",
      description:
        "The external vendor still has not approved the webhook allowlist request.",
      severity: "high",
      owner: "Ray Stone",
      status: "Watching",
      pipelineId: "automation-phase",
      teamId: "automation",
    },
    {
      id: "or2",
      kind: "risk",
      title: "Training review lag",
      description:
        "Internal review on the enablement deck is slower than planned.",
      severity: "medium",
      owner: "Jade Moss",
      status: "Mitigating",
      pipelineId: "handoff-phase",
      teamId: "enablement",
    },
    {
      id: "or3",
      kind: "issue",
      title: "Ownership table missing support lane",
      description:
        "The current ownership matrix still needs the support escalation path.",
      severity: "medium",
      owner: "Kemi Fox",
      status: "Open",
      pipelineId: "process-phase",
      teamId: "ops",
    },
  ],
  activities: [
    {
      id: "oa1",
      actor: "Kemi Fox",
      actorInitials: "KF",
      summary:
        "updated the approval checklist after the latest operator review.",
      createdAt: "3h ago",
      pipelineId: "process-phase",
      teamId: "ops",
    },
    {
      id: "oa2",
      actor: "Ray Stone",
      actorInitials: "RS",
      summary: "paused the webhook pilot while the vendor approval is pending.",
      createdAt: "Today",
      pipelineId: "automation-phase",
      teamId: "automation",
    },
    {
      id: "oa3",
      actor: "Jade Moss",
      actorInitials: "JM",
      summary: "moved the training deck into internal review.",
      createdAt: "Yesterday",
      pipelineId: "handoff-phase",
      teamId: "enablement",
    },
  ],
  teams: [
    {
      id: "ops",
      name: "Operations",
      focus: "Process ownership and approval flow",
      memberIds: ["o1", "o3"],
      pipelineIds: ["process-phase", "handoff-phase"],
      taskCounts: opsWorkflows[0].taskCounts,
      progress: 72,
      dueWindow: "Feb 12 - Mar 14",
    },
    {
      id: "automation",
      name: "Automation",
      focus: "Pilot triggers and fallback logic",
      memberIds: ["o2"],
      pipelineIds: ["automation-phase"],
      taskCounts: opsWorkflows[1].taskCounts,
      progress: 36,
      dueWindow: "Mar 1 - Mar 26",
    },
    {
      id: "enablement",
      name: "Enablement",
      focus: "Training, documentation, and rollout prep",
      memberIds: ["o3", "o4"],
      pipelineIds: ["automation-phase", "handoff-phase"],
      taskCounts: opsWorkflows[2].taskCounts,
      progress: 44,
      dueWindow: "Mar 10 - Apr 4",
    },
  ],
  heatmap: createHeatmap(
    [1, 3, 6, 8, 10, 14, 17, 20, 24, 28],
    [11, 16, 23, 29],
  ),
  workflows: opsWorkflows,
};

export const projectOverviewRecords: Record<string, ProjectOverviewRecord> = {
  [mobileApp.id]: mobileApp,
  [growthCampaign.id]: growthCampaign,
  [opsCommand.id]: opsCommand,
};

export const projectSidebarItems = Object.values(projectOverviewRecords).map(
  (project) => ({
    id: project.id,
    name: project.name,
    emoji: project.emoji,
    href: getProjectRoute(project.id),
    pipelines: project.pipelines.map((pipeline) => ({
      id: pipeline.id,
      name: pipeline.name,
      href: `${getProjectRoute(project.id)}?pipeline=${pipeline.id}`,
    })),
  }),
);
